import Head from 'next/head';
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHome, faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Vlad&#39;s NextJS Game Store</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav className='navbar bg-lgray'>
        <div className='home-link'>
          <Link href='/'>
            <FontAwesomeIcon icon={faHome} />
          </Link>
        </div>
        <form className='search-form'>
          <input type='search' name='search' id='' placeholder='Search' />
          <button type='submit'>
            <FontAwesomeIcon icon={faMagnifyingGlass} />
          </button>
        </form>
        <ul>
          <li>
            <Link href='/register'>Register</Link>
          </li>
          <li>
            <Link href='/login'>Login</Link>
          </li>
        </ul>
      </nav>

      {children}
    </>
  );
}
