import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar bg-lgray"></nav>
      <div className="cart-container"></div>
      <section className='container'>
        <div className="games-list">
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
        </div>
      </section>
    </>
  )
}
