import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { fetchGames } from '../lib/api-calls'

export async function getStaticProps() {
  const games: Array<object> = await fetchGames();
  return {
    props: {
      games
    }
  }
}

export default function Home({ games }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar bg-lgray">
        <div className="home-link">
          <a href="#">H</a>
        </div>
        <form className="search-form">
          <input type="search" name="search" id="" placeholder='Search' />
          <button type="submit">S</button>
        </form>
        <ul>
          <li>
            <a href="#">Link 1</a>
          </li>
          <li>
            <a href="#">Link 2</a>
          </li>
        </ul>
      </nav>

      <div className="cart-container"></div>

      <section className='container'>
        <div className="games-list">
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
          <div className="game-item">
            <a href="#">
              <Image src="https://i.imgur.com/c0fZxQC.jpg" alt="Detroit: Become Human" width={220} height={280} />
              <h3>Detroit: Become Human</h3>
              <span className="list-price">40</span>
            </a>
          </div>
        </div>
      </section>
    </>
  )
}
